language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose -f docker/docker-compose.yml run web bash -c "python -Wd manage.py test && flake8"
